services:
  backend:
    build:
      context: backend
      dockerfile: src\main\docker\Dockerfile.jvm
    image: rutven/test-backend
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://backend-db:5432/quarkus
    ports:
      - "8080:8080"
    depends_on:
      backend-db:
        condition: service_healthy
    networks:
      - backend-net

  backend-db:
    image: "postgres:15.4"
    environment:
      - POSTGRES_USER=quarkus
      - POSTGRES_PASSWORD=quarkus
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quarkus"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 15s
    ports:
      - "5432:5432"
    networks:
      - backend-net

networks:
  backend-net: